#!/bin/sh

test_fmt() {
    IFS=$'\n'
    for file in $(git diff --cached --name-only | grep '\.go$')
    do
        if test "$(git cat-file -p :$file | gofmt -l)" = "<standard input>"
        then
            list="${list}${file}\n"
        fi
    done
    if test -n "$list"
    then
        echo "gofmt needs to format these files (run gofmt -w):"
        printf "$list"
        exit 1
    fi
}

case "$1" in
    --about )
        echo "Check Go code formatting"
        ;;
    * )
        test_fmt
        ;;
esac
