#!/bin/sh
# NOTE: This script does not play well when adding partial changes, such as with
# git add -p or git commit -p.

test_fmt() {
    hash gofmt 2>&- || { echo >&2 "gofmt not in PATH."; exit 1; }
    IFS='
'
    for file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
    do
        gofmt -w "$file"
        git add "$file"
    done
}

case "$1" in
    --about )
        echo "Check Go code formatting"
        ;;
    * )
        test_fmt
        ;;
esac
