#!/bin/sh

test_fmt() {
    hash gofmt 2>&- || { echo >&2 "gofmt not in PATH."; exit 1; }
    IFS='
'
    for file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
    do
        if test "$(git cat-file -p :$file | gofmt -l)" = "<standard input>"
        then
            list="${list}${file}\n"
        fi
    done
    if test -n "$list"
    then
        echo >&2 "gofmt needs to format these files (run gofmt -w):"
        printf "$list"
        exit 1
    fi
}

case "$1" in
    --about )
        echo "Check Go code formatting"
        ;;
    * )
        test_fmt
        ;;
esac
