#!/bin/sh

test_fmt() {
    IFS=$'\n'
    for file in $(git diff --cached --name-only | grep '\.go$')
    do
        if test -n "$(gofmt -l "$file")"
        then
            if test ! -n "$list"
            then
                list="$file"
            else
                list="$list\n$file"
            fi
        fi
    done
    if test -n "$list"
    then
        echo "gofmt needs to format these files (run gofmt -w):"
        echo -e $list
        exit 1
    fi
}

case "$1" in
    --about )
        echo "Check Go code formatting"
        ;;
    * )
        test_fmt
        ;;
esac
